name: Docker Image CI

on:
  push:
    branches: [main, dev]
    paths:
      - 'Dockerfile'

jobs:
  build-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        Plan: [amd64, arm64]

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ghcr.io/${{ github.repository }}:${{matrix.Plan}}
          platforms: linux/${{matrix.Plan}}
          cache-from: type=gha,scope=${{matrix.Plan}}
          cache-to: type=gha,mode=max,scope=${{matrix.Plan}}
          push: true
      - name: Test
        run: |
          docker run --rm -v $(pwd):/app ghcr.io/${{ github.repository }}:${{matrix.Plan}}
          docker image ls

  release-image:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: test-image
        run: |
          docker manifest create ghcr.io/${{ github.repository }}:latest --amend ghcr.io/${{ github.repository }}:amd64 --amend ghcr.io/${{ github.repository }}:arm64
          docker manifest push ghcr.io/${{ github.repository }}:latest
